### ISSUE TITLE
Problem npm start

### ISSUE THREAD

**Issue by fap48nt** [baseljs/basel#25]
fap48nt@fap48nt-Aspire-ES1-572:~/BaselApps/Ejemplo$ npm start

> Ejemplo@0.0.2 start /home/fap48nt/BaselApps/Ejemplo
> electron main.js

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/fap48nt/BaselApps/Ejemplo/node_modules/electron-prebuilt/path.txt'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/home/fap48nt/BaselApps/Ejemplo/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Ejemplo@0.0.2 start: `electron main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Ejemplo@0.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fap48nt/.npm/_logs/2018-05-30T13_20_24_546Z-debug.log

**Comment by fap48nt** [comment]
Change the package.json "devDependecnies" generated from this
"devDependencies": {
        "electron-prebuilt": "1.4.13",
        "electron-packager": "6.0.0",
        "basel-cli": "*",
        "jquery": "2.2.4",
        "angular": "1.5.1",
        "angular-route": "1.5.1",
        "angular-utils-pagination": "0.11.0"
    },
to
"devDependencies": {
        "electron": "2.0.0",
        "electron-packager": "6.0.0",
        "basel-cli": "*",
        "jquery": "2.2.4",
        "angular": "1.5.1",
        "angular-route": "1.5.1",
        "angular-utils-pagination": "0.11.0"
    },
to resolve the problem
