### ISSUE TITLE
Exception During Basel Init

### ISSUE THREAD

**Issue by isparia** [baseljs/basel#28]
During Project Init i get the following Exception:
![image](https://user-images.githubusercontent.com/30974730/60106699-f0442680-9765-11e9-836d-93a45acf4bcd.png)

For my Environment: 
WIN 10 PRO x64

NPM Version: 6.9.0
NG Version: 
![image](https://user-images.githubusercontent.com/30974730/60106236-23d28100-9765-11e9-93bb-0cf5b0e09141.png)

SQLite:
sqlite-sync@0.3.8
sqlite-cipher@0.3.6
sqlite@3.0.3

Any Ideas or Suggestions?

**Comment by marturojt** [comment]
=( I have the same issue on MacOS

#############################################

  Congratulations you have basel-io installed.

/usr/local/lib/node_modules/basel/node_modules/sqlite-sync/sqlite.js:79
                        throw x;
                        ^

TypeError: SQL.Database is not a constructor
    at sqlite.connect (/usr/local/lib/node_modules/basel/node_modules/sqlite-sync/sqlite.js:76:14)
    at Object.exports.init (/usr/local/lib/node_modules/basel/lib/database.js:26:15)
    at /usr/local/lib/node_modules/basel/lib/install.js:66:16
    at /usr/local/lib/node_modules/basel/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:290:7)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)

**Comment by dylan-k** [comment]
Same issue here on Mac OS.
```
~/.nvm/versions/node/v10.16.0/lib/node_modules/basel/node_modules/sqlite-sync/sqlite.js:79
TypeError: SQL.Database is not a constructor
```

node: 10.16.0
sqlite: 3.19.3
npm: 6.9.0
